Repository ACS330-Collaborative-Robotics/Multi-Robot-Collaboration, pull requests merged in 2023-03, with the labels that each got.

#36 Fixing kinematic chain
  docs/node_graph.png
  docs/path_planner_class_diagram.png
  readme.md
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/scripts/spawn_blocks.py
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/joint_controller/scripts/joint_controller.py
  src/movement_demo/CMakeLists.txt
  src/movement_demo/scripts/test_kinematic_chain.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/path_planning/scripts/path_plan.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PathPlanner.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#37 New Inverse Kinematics Service
  readme.md
  src/assignment_selection/scripts/block_selection.py
  src/inv_kinematics/CMakeLists.txt
  src/inv_kinematics/package.xml
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/inv_kinematics/src/inverse_kinematics_service.cpp
  src/path_planning/src/path_planner/PickUp.py
Labels: Conor

#44 Inverse Kinematics Tolerance Fixes
  src/assignment_selection/scripts/block_selection.py
  src/inv_kinematics/CMakeLists.txt
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/inv_kinematics/src/inverse_kinematics_service.cpp
  src/inv_kinematics/urdf/CPRMover6.urdf.xacro
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#43 Rotating Simulation Robots
  src/mover6_gazebo/launch/mover6_gazebo.launch
Labels: Tom

#46 Improved Random Block Placements
  src/block_controller/scripts/spawn_blocks.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/mover6_gazebo/scripts/static_tf2_broadcaster.py
Labels: Conor

#47 IK Diagnostics & Fixes
  src/assignment_selection/scripts/block_selection.py
  src/inv_kinematics/scripts/inv_kin_srv.py
Labels: Conor

#52 Selective joint inverse kinematics & Rospy Debug
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/scripts/spawn_blocks.py
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/joint_controller/scripts/gripper_controller.py
  src/joint_controller/scripts/joint_controller.py
  src/movement_demo/scripts/test_kinematic_chain.py
  src/path_planning/scripts/path_plan.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PathPlanner.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#42 Intelligent Block Selection
  src/assignment_selection/CMakeLists.txt
  src/assignment_selection/scripts/basic_block_selection.py
  src/assignment_selection/scripts/block_selection.py
  src/assignment_selection/scripts/test_arrays.py
  src/path_planning/src/path_planner/PathPlanner.py
  src/path_planning/src/path_planner/PlaceDown.py
Labels: Annan

#56 Convert Path Planner from Service to Action
  src/assignment_selection/CMakeLists.txt
  src/assignment_selection/package.xml
  src/assignment_selection/scripts/block_selection.py
  src/path_planning/CMakeLists.txt
  src/path_planning/action/PathPlan.action
  src/path_planning/package.xml
  src/path_planning/scripts/path_plan.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PathPlanner.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/PlaceDown.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#25 Sim Gripper V2
  src/joint_controller/scripts/gripper_controller.py
  src/mover6_control/config/mover6_a_control.yaml
  src/mover6_control/config/mover6_b_control.yaml
  src/mover6_control/launch/mover6_control.launch
  src/mover6_description/launch/mover6.rviz
  src/mover6_description/meshes/gripper_a.STL
  src/mover6_description/meshes/gripper_b.STL
  src/mover6_description/meshes/joint7.STL
  src/mover6_description/urdf/CPRMover6.urdf.xacro
  src/mover6_gripper/CMakeLists.txt
  src/mover6_gripper/config/joint_names_GreiferZF_2016.yaml
  src/mover6_gripper/export.log
  src/mover6_gripper/launch/display.launch
  src/mover6_gripper/launch/gazebo.launch
  src/mover6_gripper/meshes/base_link.STL
  src/mover6_gripper/meshes/gripper_a.STL
  src/mover6_gripper/meshes/gripper_b.STL
  src/mover6_gripper/package.xml
  src/mover6_gripper/scripts/close_a.py
  src/mover6_gripper/scripts/close_b.py
  src/mover6_gripper/scripts/open_a.py
  src/mover6_gripper/scripts/open_b.py
  src/mover6_gripper/urdf/GreiferZF_2016.SLDASM.csv
  src/mover6_gripper/urdf/GreiferZF_2016.SLDASM.urdf
Labels: Andrei

#35 Human Detection with LIDAR
  src/human_zone/CMakeLists.txt
  src/human_zone/package.xml
  src/human_zone/scripts/human_detection.py
Labels: Hanin
