Repository ACS330-Collaborative-Robotics/Multi-Robot-Collaboration, pull requests merged in 2023-04, with the labels that each got.

#61 Joint Behaviour Test
  readme.md
  src/movement_demo/CMakeLists.txt
  src/movement_demo/launch/kinematics_nodes.launch
  src/movement_demo/scripts/joint_behaviour_test.py
Labels: Conor

#63 Overhaul kinematics system tests
  readme.md
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/movement_demo/CMakeLists.txt
  src/movement_demo/scripts/basic_kinematic_movement.py
  src/movement_demo/scripts/inverse_kinematic_test.py
  src/movement_demo/scripts/joint_sweep_test.py
  src/movement_demo/scripts/kinematics_movement_demo.py
  src/movement_demo/scripts/path_planner_test.py
  src/movement_demo/scripts/test_kinematic_chain.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/PlaceDown.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#67 Path Planner Block Interactions
  readme.md
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/CMakeLists.txt
  src/block_controller/scripts/block_pos_talker.py
  src/block_controller/scripts/spawn_blocks.py
  src/block_controller/scripts/spawn_test_block.py
  src/block_controller/urdf/block.urdf
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/joint_controller/scripts/gripper_controller.py
  src/joint_controller/scripts/manual_gripper_control_a.py
  src/joint_controller/scripts/manual_gripper_control_b.py
  src/movement_demo/CMakeLists.txt
  src/movement_demo/scripts/joint_position_debug.py
  src/mover6_gazebo/launch/mover6_gazebo_no_blocks.launch
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/PlaceDown.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#65 Intelligent, Multi-Robot Assignment Selection
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/urdf/block.urdf
  src/movement_demo/launch/movement_demo.launch
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor, Annan

#71 System tweaks
  catkin_make_pi.sh
  readme.md
  run_fiducial_recognition.sh
  run_sim_phys.sh
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/scripts/spawn_blocks.py
  src/gui/scripts/GUI.py
  src/joint_controller/src/mover6_driver.cpp
  src/movement_demo/CMakeLists.txt
  src/movement_demo/launch/movement_demo.launch
  src/movement_demo/scripts/joint_behaviour_test.py
  src/movement_demo/scripts/physical_robot_homing.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/mover6_gazebo/launch/mover6_gazebo_no_blocks.launch
  src/mover6_gazebo/launch/mover6_gazebo_phys.launch
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor, Tom

#73 System Tweaks 2
  clear_workspace.sh
  is_blocks_vis.sh
  readme.md
  run_fiducial_recognition.sh
  src/apriltag_ros/config/tags.yaml
  src/assignment_selection/CMakeLists.txt
  src/assignment_selection/launch/test_reach.launch
  src/assignment_selection/scripts/basic_block_selection.py
  src/assignment_selection/scripts/block_selection.py
  src/assignment_selection/scripts/test_block_reachability.py
  src/block_controller/scripts/spawn_blocks.py
  src/block_controller/scripts/update_blocks_phys.py
  src/e_stop/CMakeLists.txt
  src/e_stop/scripts/e_stop.py
  src/e_stop/scripts/e_stop_controller.py
  src/e_stop/scripts/e_stop_manual.py
  src/fiducial_recognition/launch/sensor_launch.launch
  src/human_zone/launch/lidar_launch.launch
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/joint_controller/src/mover6_driver.cpp
  src/movement_demo/CMakeLists.txt
  src/movement_demo/scripts/joint_behaviour_test.py
  src/movement_demo/scripts/robot_homing.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/mover6_gazebo/launch/mover6_gazebo_no_blocks.launch
  src/mover6_gazebo/launch/mover6_gazebo_phys.launch
  src/path_planning/scripts/path_plan.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/PlaceDown.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor, Tom

#74 Assignment Selector Fixes
  src/assignment_selection/scripts/block_selection.py
  src/block_controller/scripts/spawn_blocks.py
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#33 Potential fields
  .gitignore
  run_demo_path_test.sh
  run_sim_path_test.sh
  src/assignment_selection/scripts/block_selection.py
  src/assignment_selection/scripts/test_block_reachability.py
  src/block_controller/scripts/spawn_blocks.py
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/inv_kinematics/srv/InvKin.srv
  src/movement_demo/launch/movement_demo_APF.launch
  src/mover6_gazebo/launch/mover6_gazebo.launch
  src/mover6_gazebo/launch/mover6_gazebo_no_blocks.launch
  src/path_planning/CMakeLists.txt
  src/path_planning/config/settings.yaml
  src/path_planning/launch/movement_demo.launch
  src/path_planning/launch/mover6_gazebo_path_test.launch
  src/path_planning/scripts/path_plan.py
  src/path_planning/scripts/path_plan_test.py
  src/path_planning/scripts/path_plan_test2.0.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PathPlanner.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/PlaceDown.py
  src/path_planning/src/path_planner/ServiceHelper.py
  src/path_planning/test_scripts/APF_Controller.py
  src/path_planning/test_scripts/APF_Path.py
  src/path_planning/test_scripts/APF_Path_Dynamic.py
  src/path_planning/test_scripts/BotRoute.xlsx
  src/path_planning/test_scripts/Distance_Euclidian.py
  src/path_planning/test_scripts/Object_Creation.py
  src/path_planning/test_scripts/Path_Noise.py
  src/path_planning/test_scripts/Potential_Attractions.py
  src/path_planning/test_scripts/Potential_Fields_Prototyping.py
  src/path_planning/test_scripts/Potential_Repulsion.py
  src/path_planning/test_scripts/Potential_Repulsion_Updated.py
  src/path_planning/test_scripts/Reset_Excel_Data
  src/path_planning/test_scripts/Testing.xlsx
  src/path_planning/test_scripts/Visualiser.py
  src/path_planning/test_scripts/testing file.py
Labels: Joe, Steve

#75 Consolidating and fixing reachability
  src/assignment_selection/scripts/block_selection.py
  src/assignment_selection/scripts/test_block_reachability.py
  src/inv_kinematics/scripts/inv_kin_srv.py
  src/path_planning/scripts/path_plan.py
  src/path_planning/src/path_planner/Movement.py
  src/path_planning/src/path_planner/PickUp.py
  src/path_planning/src/path_planner/ServiceHelper.py
Labels: Conor

#66 Updated nodes configured light and started error status light
  src/e_stop/scripts/e_stop_manual.py
  src/gui/scripts/GUI.py
  src/gui/scripts/checkSim.py
  src/mover6_gazebo/launch/mover6_gazebo.launch
Labels: Wiks
